on: [push]

name: "Foundry CI"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: |
          which forge
          ls -l
          forge test -vvv

      - name: Run snapshot
        run: forge snapshot
